### ISSUE TITLE
Documentation errors for Salt Sentry manual

### ISSUE THREAD

**Issue by falz** [Lemcke-solutions/SaltSentryManuals#1]
I just set this device up, and since it was my first time with Home Assistant and MQTT, I was struggling. There are a few issues with the manual that I'd suggest be updated.

It may be nice to add clarity of what fields in Home Assistant's `configuration.yaml` line up with the fields in the Salt Sentry web gui. I found that the 'mqtt topic' made sense to just call "saltsentry" and then have the configuration.yaml match, as below:

![saltsentry-connected](https://user-images.githubusercontent.com/707319/215293239-2a7a3027-d589-4f52-8717-b34e0036b98d.png)

```yaml
mqtt:
 sensor:
 - name: "Salt Sentry percent"
   state_topic: "saltsentry"
   unit_of_measurement: "%"
 - name: "Salt Sentry distance"
   state_topic: "saltsentry_distance"
   unit_of_measurement: "cm"
```

Also note that the yaml in the guide has issues. The yaml above seems to be correct from what I can tell.
1) yaml formatting - it shows two different **mqtt:** and **sensor:** sections. If you want to use both one must combine them, per above
2) Uppercase **S**ensor vs **s**ensor. Uppercase not allowed
3) Quotation Marks - Standard **"** required but several in the guide are **”** which are not the same character
4) this is cosmentic, but the first sensor I named with a "percent" suffix, which seems to be more apples to apples with the naming of the "distance" sensor.

Cheers
